apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../alpha
patchesStrategicMerge:
- controller_always_pull.yaml
- node_always_pull.yaml
namespace: gce-pd-csi-driver
transformers:
- ../../images/dev
images:
- name: gke.gcr.io/gcp-compute-persistent-disk-csi-driver
  newName: gcr.io/mattcary-gke-dev-owned/csi/gce-pd-driver
  newTag: latest
